# STAT5106 Programming Techniques for Data Science Assignment 3_Python

## Content
<p>1. Introduction</p>
<p>2. Learning Outcomes</p>
<p>3. Assignment 3</p>

## 1. Introduction

<p>This course teaches programming fundamentals for data scientists. Students can learn programming techniques with emphasis on data source connection, data pre-processing pipeline, exploratory data analysis, data visualisations and data reporting.</p>

## 2. Learning Outcomes

<p>To get the techniques for data anlysis with the application of R and Python, such as data import from multiple sources, data pre-processing, statistical analysis, etc.</p>

## 3. Assignment 3

<p>To plot and do analysis by Python.</p>

In [2]:
#Question 2
#US Census Aggregated Dataset

#Import packages

import pandas as pd
import numpy as np

#Read file
census_df = pd.read_csv("census.csv")
census_df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

In [5]:
#Question A: Which state has the most counties in it?
#Filter sumlev=50
#Count no. of sumlev by state names
#Return the max. value with state name and no. of sumlev
def questionA():
    a=census_df[census_df['SUMLEV']==50]
    a=a.groupby('STNAME').count()['SUMLEV']
    return a[a==a.max()]
questionA()

STNAME
Texas    254
Name: SUMLEV, dtype: int64

In [4]:
#Question B: The three most populous states (which count the population in all of the constitute counties)
#COUNTY == 0 means the whole state in this dataset.
#Filter sumlev=50
#Sum census2010pop by state names
#Return top three 
def questionB():
    b=census_df[census_df['SUMLEV']==50]
    b=b.groupby('STNAME').sum()['CENSUS2010POP'].nlargest(n=3)
    return b
questionB()

STNAME
California    37253956
Texas         25145561
New York      19378102
Name: CENSUS2010POP, dtype: int64

In [6]:
#Question C: Which county has had the largest absolute change in population within the period 2010-2015?
#Filter sumlev=50
#Find the max. and min. values in population within the period 2010-2015 & calculate the largest absolute change
#Find the largest absolute change of county
def questionC():
    c=census_df[census_df['SUMLEV']==50]
    c=c[['CTYNAME','POPESTIMATE2010', 'POPESTIMATE2011','POPESTIMATE2012','POPESTIMATE2013','POPESTIMATE2014','POPESTIMATE2015']]
    max_c=map(max,c['POPESTIMATE2010'],c['POPESTIMATE2011'],c['POPESTIMATE2012'],c['POPESTIMATE2013'],c['POPESTIMATE2014'],c['POPESTIMATE2015'])
    max_c=np.array(list(max_c))
    min_c=map(min,c['POPESTIMATE2010'],c['POPESTIMATE2011'],c['POPESTIMATE2012'],c['POPESTIMATE2013'],c['POPESTIMATE2014'],c['POPESTIMATE2015'])
    min_c=np.array(list(min_c))
    absolute_change=max_c-min_c
    return c.iloc[absolute_change.argmax()].values[0]
questionC()

'Harris County'

In [7]:
#Question D: Create a query that finds the counties that belong to regions 1 or 2, 
#whose name starts with 'Washington', and whose POPESTIMATE2015 was greaterthan their POPESTIMATE2014 .
def questionD():
    d=census_df[(census_df['SUMLEV']==50) & (census_df['REGION']<=2) & (census_df['CTYNAME'].str.match('^Washington')) & (census_df['POPESTIMATE2015']>census_df['POPESTIMATE2014'])]
    return d
questionD()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
896,50,2,4,19,183,Iowa,Washington County,21704,21704,21697,...,5.743693,2.468684,-0.364282,0.272171,1.849596,5.881542,2.560117,-0.273212,0.408256,1.984933
1419,50,2,4,27,163,Minnesota,Washington County,238136,238134,238995,...,2.555118,3.260957,2.285952,3.072543,0.678755,4.178076,4.907905,4.009584,5.040262,2.615204
2345,50,1,2,42,125,Pennsylvania,Washington County,207820,207820,207877,...,3.683135,3.260434,1.219337,2.113561,1.656917,4.062988,3.750219,1.742595,2.762039,2.305276
2355,50,1,1,44,9,Rhode Island,Washington County,126979,127094,127085,...,-4.669304,-2.659574,1.551904,1.400112,0.506035,-3.533527,-1.788880,2.462459,2.428442,1.533918
3163,50,2,3,55,131,Wisconsin,Washington County,131887,131885,131967,...,-0.794876,0.785279,-2.215465,1.601149,-0.434498,-0.431504,1.162817,-1.763330,2.104796,0.059931